export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f7f9fb",
        "error": "#EF4444",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-high": "#e6e8ea",
        "outline": "#76777d",
        "on-primary-container": "#7c839b",
        "on-surface-variant": "#45464d",
        "tertiary": "#000000",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container-highest": "#e0e3e5",
        "on-error": "#ffffff",
        "secondary-fixed": "#d8e2ff",
        "background": "#f7f9fb",
        "tertiary-fixed-dim": "#b7c8e1",
        "inverse-surface": "#2d3133",
        "primary-fixed": "#dae2fd",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary": "#ffffff",
        "secondary": "#0058be",
        "on-tertiary-fixed": "#0b1c30",
        "secondary-fixed-dim": "#adc6ff",
        "tertiary-container": "#0b1c30",
        "error-container": "#ffdad6",
        "surface-container": "#eceef0",
        "on-secondary": "#ffffff",
        "outline-variant": "#c6c6cd",
        "warning": "#F59E0B",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#004395",
        "primary": "#000000",
        "on-background": "#191c1e",
        "surface-border": "#E2E8F0",
        "on-surface": "#191c1e",
        "on-tertiary-container": "#75859d",
        "on-secondary-container": "#fefcff",
        "success": "#10B981",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#565e74",
        "inverse-primary": "#bec6e0",
        "surface": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed": "#d3e4fe",
        "on-tertiary-fixed-variant": "#38485d",
        "primary-container": "#131b2e",
        "surface-dim": "#d8dadc",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "secondary-container": "#2170e4",
        "on-secondary-fixed": "#001a42",
        "surface-variant": "#e0e3e5"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xs": "8px",
        "container-max": "1280px",
        "xxl": "48px",
        "xl": "32px",
        "lg": "24px",
        "md": "16px",
        "xxs": "4px",
        "sm": "12px",
        "base": "4px",
        "gutter": "24px"
      },
      fontFamily: {
        "code": ["monospace"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-md": ["Inter"],
        "title-md": ["Inter"],
        "label-lg": ["Inter"],
        "body-lg": ["Inter"],
        "display-sm": ["Inter"],
        "title-sm": ["Inter"],
        "display-md": ["Inter"],
        "headline-sm": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "title-lg": ["Inter"]
      }
    },
  },
  plugins: [],
}
